plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
    id 'application'
}

group = 'com.dvas'
version = '1.1.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation(
        'org.hyperledger.fabric-chaincode-java:' +
        'fabric-chaincode-shim:2.5.10'
    )

    implementation 'com.google.code.gson:gson:2.10.1'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}

application {
    mainClass =
        'org.hyperledger.fabric.contract.ContractRouter'

    applicationName = 'dvas'
}

shadowJar {
    archiveBaseName.set('chaincode')
    archiveClassifier.set('')
    archiveVersion.set('')

    duplicatesStrategy =
        DuplicatesStrategy.INCLUDE

    mergeServiceFiles()

    manifest {
        attributes(
            'Main-Class':
                'org.hyperledger.fabric.contract.ContractRouter'
        )
    }
}